TRACKS_DB_TOKEN: Personal/tracks.stho.net/read-only-token
TRACKS_DB_URL: Personal/tracks.stho.net/url
APPLE_DEV_CERT: Personal/apple-dev/dev-cert
APPLE_DEV_CERT_PASSWORD: Personal/apple-dev/dev-cert-password
ASC_ISSUER_ID: snap-sync/appstore-connect/issuer-id
ASC_KEY_ID: snap-sync/appstore-connect/key-id
ASC_AUTH_KEY: snap-sync/appstore-connect/auth-key