TRACKS_DB_TOKEN: Personal/tracks.stho.net/db-read-only-token
TRACKS_DB_URL: Personal/tracks.stho.net/db-url
TRACKS_STORAGE_ZONE: Personal/tracks.stho.net/storage-zone
TRACKS_STORAGE_ZONE_PASSWORD: Personal/tracks.stho.net/storage-zone-password
TRACKS_STORAGE_ZONE_READ_ONLY_PASSWORD: Personal/tracks.stho.net/storage-zone-read-only-password
APPLE_DEV_CERT: Personal/apple-dev/dev-cert
APPLE_DEV_CERT_PASSWORD: Personal/apple-dev/dev-cert-password
ASC_ISSUER_ID: snap-sync/appstore-connect/issuer-id
ASC_KEY_ID: snap-sync/appstore-connect/key-id
ASC_AUTH_KEY: snap-sync/appstore-connect/auth-key